package com.mauss.edu.model;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.web.multipart.MultipartFile;

import javax.persistence.*;

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Entity
public class Materials {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    private String materialId; //todo: Auto generated by the system //DONE
    private String teachId; //todo: Auto taken from Principal Login info * //DONE
    private String classId; //todo: Auto taken from className //NOTDONE
    private String classN;

    private String courseId; //todo: Auto taken from courseName //NOTDONE
    private String courseN;
    private String title;
    private String description;
    private boolean activate; //todo: As a default it is activated or true 8 //DONE
    @Lob
    private byte[] material;
    private String fileName;

}
