package com.mauss.edu.service.impl;

import com.mauss.edu.model.Schedules;
import com.mauss.edu.repository.SchedulesRepository;
import com.mauss.edu.service.ScheduleService;
import lombok.AllArgsConstructor;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.security.Principal;
import java.time.Year;
import java.util.Random;

@Service
@AllArgsConstructor
public class ScheduleServiceImpl implements ScheduleService {

    @Autowired
    private final SchedulesRepository schedulesRepository;
    @Override
    public void saveSchedule(Schedules schedules) {
        String id = autoGeneratedId();
        schedules.setSchId(id);
        schedulesRepository.save(schedules);
    }
    String autoGeneratedId(){
        int c = schedulesRepository.findAll().size();
        String id;
        Random random = new Random();
    return id = "SCHED-"+ (c+1) + "-" + random.nextInt(10,99) + "-" + Year.now();
    }
}
